import { NavigationBar } from '@/components/NavigationBar'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <NavigationBar />
        <div className="m-auto flex items-center justify-center sm:h-screen lg:h-[calc(100vh-3.25rem)]">
          {children}
        </div>
      </body>
    </html>
  )
}
